#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp9
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="myDB")]
	public partial class myDBDataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void InsertPersons(Persons instance);
    partial void UpdatePersons(Persons instance);
    partial void DeletePersons(Persons instance);
    partial void InsertProducts(Products instance);
    partial void UpdateProducts(Products instance);
    partial void DeleteProducts(Products instance);
    #endregion
		
		public myDBDataClasses1DataContext() : 
				base(global::WindowsFormsApp9.Properties.Settings.Default.myDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public myDBDataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public myDBDataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public myDBDataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public myDBDataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Persons> Persons
		{
			get
			{
				return this.GetTable<Persons>();
			}
		}
		
		public System.Data.Linq.Table<Products> Products
		{
			get
			{
				return this.GetTable<Products>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Persons")]
	public partial class Persons : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _姓名;
		
		private string _電話;
		
		private string _地址;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _生日;
		
		private System.Nullable<bool> _婚姻狀態;
		
		private System.Nullable<int> _點數;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void On姓名Changing(string value);
    partial void On姓名Changed();
    partial void On電話Changing(string value);
    partial void On電話Changed();
    partial void On地址Changing(string value);
    partial void On地址Changed();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void On生日Changing(System.Nullable<System.DateTime> value);
    partial void On生日Changed();
    partial void On婚姻狀態Changing(System.Nullable<bool> value);
    partial void On婚姻狀態Changed();
    partial void On點數Changing(System.Nullable<int> value);
    partial void On點數Changed();
    #endregion
		
		public Persons()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_姓名", DbType="NVarChar(50)")]
		public string 姓名
		{
			get
			{
				return this._姓名;
			}
			set
			{
				if ((this._姓名 != value))
				{
					this.On姓名Changing(value);
					this.SendPropertyChanging();
					this._姓名 = value;
					this.SendPropertyChanged("姓名");
					this.On姓名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_電話", DbType="NVarChar(50)")]
		public string 電話
		{
			get
			{
				return this._電話;
			}
			set
			{
				if ((this._電話 != value))
				{
					this.On電話Changing(value);
					this.SendPropertyChanging();
					this._電話 = value;
					this.SendPropertyChanged("電話");
					this.On電話Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_地址", DbType="NVarChar(100)")]
		public string 地址
		{
			get
			{
				return this._地址;
			}
			set
			{
				if ((this._地址 != value))
				{
					this.On地址Changing(value);
					this.SendPropertyChanging();
					this._地址 = value;
					this.SendPropertyChanged("地址");
					this.On地址Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_生日", DbType="Date")]
		public System.Nullable<System.DateTime> 生日
		{
			get
			{
				return this._生日;
			}
			set
			{
				if ((this._生日 != value))
				{
					this.On生日Changing(value);
					this.SendPropertyChanging();
					this._生日 = value;
					this.SendPropertyChanged("生日");
					this.On生日Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_婚姻狀態", DbType="Bit")]
		public System.Nullable<bool> 婚姻狀態
		{
			get
			{
				return this._婚姻狀態;
			}
			set
			{
				if ((this._婚姻狀態 != value))
				{
					this.On婚姻狀態Changing(value);
					this.SendPropertyChanging();
					this._婚姻狀態 = value;
					this.SendPropertyChanged("婚姻狀態");
					this.On婚姻狀態Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_點數", DbType="Int")]
		public System.Nullable<int> 點數
		{
			get
			{
				return this._點數;
			}
			set
			{
				if ((this._點數 != value))
				{
					this.On點數Changing(value);
					this.SendPropertyChanging();
					this._點數 = value;
					this.SendPropertyChanged("點數");
					this.On點數Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Products")]
	public partial class Products : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _pname;
		
		private System.Nullable<int> _price;
		
		private string _pimage;
		
		private string _pdesc;
		
		private string _pclass;
		
		private System.Nullable<int> _pamount;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnpnameChanging(string value);
    partial void OnpnameChanged();
    partial void OnpriceChanging(System.Nullable<int> value);
    partial void OnpriceChanged();
    partial void OnpimageChanging(string value);
    partial void OnpimageChanged();
    partial void OnpdescChanging(string value);
    partial void OnpdescChanged();
    partial void OnpclassChanging(string value);
    partial void OnpclassChanged();
    partial void OnpamountChanging(System.Nullable<int> value);
    partial void OnpamountChanged();
    #endregion
		
		public Products()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pname", DbType="NVarChar(100)")]
		public string pname
		{
			get
			{
				return this._pname;
			}
			set
			{
				if ((this._pname != value))
				{
					this.OnpnameChanging(value);
					this.SendPropertyChanging();
					this._pname = value;
					this.SendPropertyChanged("pname");
					this.OnpnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
		public System.Nullable<int> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pimage", DbType="NVarChar(100)")]
		public string pimage
		{
			get
			{
				return this._pimage;
			}
			set
			{
				if ((this._pimage != value))
				{
					this.OnpimageChanging(value);
					this.SendPropertyChanging();
					this._pimage = value;
					this.SendPropertyChanged("pimage");
					this.OnpimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pdesc", DbType="NVarChar(1000)")]
		public string pdesc
		{
			get
			{
				return this._pdesc;
			}
			set
			{
				if ((this._pdesc != value))
				{
					this.OnpdescChanging(value);
					this.SendPropertyChanging();
					this._pdesc = value;
					this.SendPropertyChanged("pdesc");
					this.OnpdescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pclass", DbType="NVarChar(50)")]
		public string pclass
		{
			get
			{
				return this._pclass;
			}
			set
			{
				if ((this._pclass != value))
				{
					this.OnpclassChanging(value);
					this.SendPropertyChanging();
					this._pclass = value;
					this.SendPropertyChanged("pclass");
					this.OnpclassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pamount", DbType="Int")]
		public System.Nullable<int> pamount
		{
			get
			{
				return this._pamount;
			}
			set
			{
				if ((this._pamount != value))
				{
					this.OnpamountChanging(value);
					this.SendPropertyChanging();
					this._pamount = value;
					this.SendPropertyChanged("pamount");
					this.OnpamountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
