#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamClock
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dreamClock")]
	public partial class LinqDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertdreamMember(dreamMember instance);
    partial void UpdatedreamMember(dreamMember instance);
    partial void DeletedreamMember(dreamMember instance);
    partial void Insertimg(img instance);
    partial void Updateimg(img instance);
    partial void Deleteimg(img instance);
    #endregion
		
		public LinqDataClassesDataContext() : 
				base(global::DreamClock.Properties.Settings.Default.dreamClockConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<dreamMember> dreamMembers
		{
			get
			{
				return this.GetTable<dreamMember>();
			}
		}
		
		public System.Data.Linq.Table<memberRank> memberRanks
		{
			get
			{
				return this.GetTable<memberRank>();
			}
		}
		
		public System.Data.Linq.Table<img> imgs
		{
			get
			{
				return this.GetTable<img>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dreamMember")]
	public partial class dreamMember : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _acct;
		
		private string _pword;
		
		private int _points;
		
		private System.DateTime _lstUpdate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnacctChanging(string value);
    partial void OnacctChanged();
    partial void OnpwordChanging(string value);
    partial void OnpwordChanged();
    partial void OnpointsChanging(int value);
    partial void OnpointsChanged();
    partial void OnlstUpdateChanging(System.DateTime value);
    partial void OnlstUpdateChanged();
    #endregion
		
		public dreamMember()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acct", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string acct
		{
			get
			{
				return this._acct;
			}
			set
			{
				if ((this._acct != value))
				{
					this.OnacctChanging(value);
					this.SendPropertyChanging();
					this._acct = value;
					this.SendPropertyChanged("acct");
					this.OnacctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pword", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string pword
		{
			get
			{
				return this._pword;
			}
			set
			{
				if ((this._pword != value))
				{
					this.OnpwordChanging(value);
					this.SendPropertyChanging();
					this._pword = value;
					this.SendPropertyChanged("pword");
					this.OnpwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_points", DbType="Int NOT NULL")]
		public int points
		{
			get
			{
				return this._points;
			}
			set
			{
				if ((this._points != value))
				{
					this.OnpointsChanging(value);
					this.SendPropertyChanging();
					this._points = value;
					this.SendPropertyChanged("points");
					this.OnpointsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lstUpdate", DbType="DateTime NOT NULL")]
		public System.DateTime lstUpdate
		{
			get
			{
				return this._lstUpdate;
			}
			set
			{
				if ((this._lstUpdate != value))
				{
					this.OnlstUpdateChanging(value);
					this.SendPropertyChanging();
					this._lstUpdate = value;
					this.SendPropertyChanged("lstUpdate");
					this.OnlstUpdateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.memberRank")]
	public partial class memberRank
	{
		
		private int _threshold;
		
		private string _memRank;
		
		public memberRank()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_threshold", DbType="Int NOT NULL")]
		public int threshold
		{
			get
			{
				return this._threshold;
			}
			set
			{
				if ((this._threshold != value))
				{
					this._threshold = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_memRank", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string memRank
		{
			get
			{
				return this._memRank;
			}
			set
			{
				if ((this._memRank != value))
				{
					this._memRank = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.img")]
	public partial class img : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _imgFile;
		
		private string _msg;
		
		private string _memRank;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnimgFileChanging(string value);
    partial void OnimgFileChanged();
    partial void OnmsgChanging(string value);
    partial void OnmsgChanged();
    partial void OnmemRankChanging(string value);
    partial void OnmemRankChanged();
    #endregion
		
		public img()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgFile", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string imgFile
		{
			get
			{
				return this._imgFile;
			}
			set
			{
				if ((this._imgFile != value))
				{
					this.OnimgFileChanging(value);
					this.SendPropertyChanging();
					this._imgFile = value;
					this.SendPropertyChanged("imgFile");
					this.OnimgFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msg", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string msg
		{
			get
			{
				return this._msg;
			}
			set
			{
				if ((this._msg != value))
				{
					this.OnmsgChanging(value);
					this.SendPropertyChanging();
					this._msg = value;
					this.SendPropertyChanged("msg");
					this.OnmsgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_memRank", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string memRank
		{
			get
			{
				return this._memRank;
			}
			set
			{
				if ((this._memRank != value))
				{
					this.OnmemRankChanging(value);
					this.SendPropertyChanging();
					this._memRank = value;
					this.SendPropertyChanged("memRank");
					this.OnmemRankChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
