//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persons
    {
        public int id { get; set; }
        public string 姓名 { get; set; }
        public string 電話 { get; set; }
        public string 地址 { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> 生日 { get; set; }
        public Nullable<bool> 婚姻狀態 { get; set; }
        public Nullable<int> 點數 { get; set; }
    }
}
