//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int id { get; set; }
        public string pname { get; set; }
        public Nullable<int> price { get; set; }
        public string pimage { get; set; }
        public string pdesc { get; set; }
        public string pclass { get; set; }
        public Nullable<int> pamount { get; set; }
    }
}
